---
service: wspoc

package:
  exclude:
    - tags
    - tags.*

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}

  websocketsApiName: wspoc-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.action

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'Fn::GetAtt':
          - ConnectionTable
          - Arn

  environment:
    CONNECTION_TABLE: ConnectionTable-${self:provider.stage}

resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionTable-${self:provider.stage}

        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S

        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  connect:
    handler: src/connect.handler
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: src/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  default:
    handler: src/default.handler
    events:
      - websocket:
          route: $default
